test: fix support for coverage and pytest
Update coverage.svg

Update coverage.yml

Update coverage.yml

Update to feedback

Update coverage.yml

Update test params according to feedback

Update coverage.yml

Update coverage badge version

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

Update coverage.yml

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -1,18 +1,22 @@
 name: coverage
 on:
   pull_request:
-    branches: 
+    branches:
+      - 'master'
+  push:
+    branches:
       - 'master'
 jobs:
   build:
     runs-on: ubuntu-18.04
     env:
-      OS: ubuntu-latest
+      OS: ubuntu-18.04
       PYTHON: '3.6'
+      COVERAGE_TOTAL: 24 #Coverage threshold percentage
     steps:
     - uses: actions/checkout@master
       with:
-        fetch-depth: ‘2’
+        fetch-depth: ‘2’ #Original commit + code cov badge commit
     - name: Setup Python
       uses: actions/setup-python@master
       with:
@@ -22,22 +26,38 @@ jobs:
         python -m pip install --upgrade pip
         pip install cython==0.29.21 numpy==1.19.4
         pip install -r requirements.txt
-        pip install flake8 pytest pytest-cov
         pip install coverage-badge
-    - name: Run coverage test
-      run: |
         coverage run -m pytest
-    - name: Build coverage file
-      run: |
-        pytest --cache-clear --cov=app test/ > pytest-coverage.txt
-      run: |
-        pytest --cache-clear --cov=app test/ > pytest-coverage.txt
-    - name: Comment coverage
-      uses: coroo/pytest-coverage-commentator@v1.0.2
-    - name: Coverage Badge
-      uses: tj-actions/coverage-badge-py@v1.2
+        coverage-badge -f -o docs/coverage.svg
     - name: Verify Changed files
       uses: tj-actions/verify-changed-files@v6
       id: changed_files
       with:
-        files: coverage.svg
+        files: docs/coverage.svg
+    - name: Commit code coverage badge
+      if: ${{ steps.changed_files.outputs.files_changed == 'true' && github.event_name != 'pull_request'}}
+      run: |
+        git config --local user.email "github-actions[bot]@users.noreply.github.com"
+        git config --local user.name "github-actions[bot]"
+        git add docs/coverage.svg
+        git commit -m "test: update coverage.svg"
+    - name: Push code coverage badge
+      if: ${{ steps.changed_files.outputs.files_changed == 'true' && github.event_name != 'pull_request'}}
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.github_token }}
+        branch: ${{ github.event.pull_request.head.repo.full_name }}
+
+    - name: Coverage testing
+      if: github.event_name == 'pull_request'
+      id: pytester-cov
+      uses: alexanderdamiani/pytester-cov@v1.2.0
+      with:
+        pytest-root-dir: './dgp'
+        cov-omit-list: 'tests/*, docs/*, dgp/contribs/pd/*, dgp/proto/*'
+        cov-threshold-total: ${{ env.COVERAGE_TOTAL }}
+    - name: Coverage total fail - exit
+      if: ${{github.event_name == 'pull_request' && steps.pytester-cov.outputs.cov-threshold-total-fail == 'false' }}
+      run: |
+        echo "cov single fail ${{ steps.pytester-cov.outputs.cov-threshold-total-fail }}"
+        exit 1
